name: Deploy to Production

on:
  release:
    types: 
      - published

jobs:
  deploy:
    if: github.ref == 'refs/heads/main' # Replace 'main' with your specific branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
