name: Deploy to Production

on:
  release:
    types: 
      - published
    branches:
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
